# sopc2dts - Devicetree generation for Altera systems
#
# Original work Copyright (C) 2011-2015 Walter Goossens <waltergoossens@home.nl>
# Python port Copyright (C) 2026 Laurence <laurence@anodes4life.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

"""
Port of sopc2dts.generators.AbstractSopcGenerator.
Base class for all output generators.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from datetime import datetime
from typing import Optional, TYPE_CHECKING

from ..model.system import AvalonSystem

if TYPE_CHECKING:
    from ..model.boardinfo import BoardInfo
    from ..model.component import BasicComponent


class AbstractSopcGenerator(ABC):
    """
    Base class for all sopc2dts generators.
    Port of sopc2dts.generators.AbstractSopcGenerator.
    """

    _copyright_notice: str = (
        "/*\n"
        " * Copyright (C) 2010-2013 Walter Goossens <waltergoossens@home.nl>.\n"
        " *\n"
        " * This program is free software; you can redistribute it and/or modify\n"
        " * it under the terms of the GNU General Public License as published by\n"
        " * the Free Software Foundation; either version 2 of the License, or\n"
        " * (at your option) any later version.\n"
        " *\n"
        " * This program is distributed in the hope that it will be useful, but\n"
        " * WITHOUT ANY WARRANTY; without even the implied warranty of\n"
        " * MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE, GOOD TITLE or\n"
        " * NON INFRINGEMENT.  See the GNU General Public License for more\n"
        " * details.\n"
        " *\n"
        " * You should have received a copy of the GNU General Public License\n"
        " * along with this program; if not, write to the Free Software\n"
        " * Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.\n"
        " *\n"
        " */\n"
    )

    def __init__(self, sys: AvalonSystem, is_text: bool) -> None:
        self.sys = sys
        self.generate_text_output = is_text

    # ------------------------------------------------------------------
    # Abstract interface
    # ------------------------------------------------------------------

    @abstractmethod
    def get_text_output(self, bi: "BoardInfo") -> Optional[str]: ...

    def get_binary_output(self, bi: "BoardInfo") -> Optional[bytes]:
        """Default: encode text output as UTF-8 bytes."""
        text = self.get_text_output(bi)
        return text.encode("utf-8") if text is not None else None

    def is_text_output(self) -> bool:
        return self.generate_text_output

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def get_small_copyright_notice(
        component_name: str,
        include_time: bool = True,
    ) -> str:
        """Port of AbstractSopcGenerator.getSmallCopyRightNotice."""
        time_str = (" on " + datetime.now().strftime("%a %b %d %H:%M:%S %Z %Y")) if include_time else ""
        return (
            "/*\n"
            f" * This {component_name} is generated by sopc2dts version "
            f"{AvalonSystem.get_sopc2dts_version()}{time_str}\n"
            " * Original sopc2dts by Walter Goossens <waltergoossens@home.nl>\n"
            " * Python port by Laurence <laurence@anodes4life.com>\n"
            " * https://github.com/LaurenceA4L/sopc2dts\n"
            " */\n"
        )

    @staticmethod
    def definenify(in_str: str) -> str:
        """Port of AbstractSopcGenerator.definenify — C-preprocessor-safe name."""
        return in_str.upper().replace("-", "_").replace(" ", "_")

    def get_pov_component(self, bi: "BoardInfo") -> Optional["BasicComponent"]:
        """
        Find the Point-Of-View component as described in BoardInfo.
        Port of AbstractSopcGenerator.getPovComponent.
        """
        from ..log import logger
        from ..model.boardinfo import PovType

        pov_comp = self.sys.get_component_by_name(bi.get_pov() or "")

        if pov_comp is None:
            pov = bi.get_pov()
            if pov is None or pov == "":
                logger.info("No point of view specified. Trying to find one.")
            else:
                logger.warning(
                    "Point of view '%s' could not be found. Trying to find another.", pov
                )
            masters = self.sys.get_master_components()
            if not masters:
                logger.error("System appears to not contain any master components!")
                return None

            pov_type = bi.get_pov_type()
            if pov_type == PovType.CPU:
                for comp in masters:
                    if comp.scd.group == "cpu":
                        logger.info(
                            "Found a cpu of type %s named %s",
                            comp.class_name, comp.instance_name,
                        )
                        return comp
            elif pov_type == PovType.PCI:
                for comp in masters:
                    if "pci" in comp.scd.group.lower():
                        return comp
                for comp in masters:
                    if "pci" in comp.class_name.lower():
                        return comp
                for comp in masters:
                    if "pci" in comp.instance_name.lower():
                        logger.warning(
                            "Found PCI-like master %s (%s)",
                            comp.class_name, comp.instance_name,
                        )
                        return comp

            pov_comp = masters[0]
            logger.warning(
                "Unable to find master of type %s. Selecting first master: %s",
                pov_type.name if pov_type else "?",
                pov_comp.instance_name,
            )

        return pov_comp
