# sopc2dts - Devicetree generation for Altera systems
#
# Original work Copyright (C) 2011 Walter Goossens <waltergoossens@home.nl>
# Python port Copyright (C) 2026 Laurence <laurence@anodes4life.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

"""
Port of sopc2dts.generators.SopcCreateHeaderFilesImitator.

Mimics sopc-create-header-files output: a C header with CMacro defines
for every component reachable from the POV master.
"""

from __future__ import annotations

from typing import Optional, Set, TYPE_CHECKING

from .AbstractSopcGenerator import AbstractSopcGenerator
from ..model.enums import SystemDataType

if TYPE_CHECKING:
    from ..model.boardinfo import BoardInfo
    from ..model.system import AvalonSystem
    from ..model.component import BasicComponent, Interface


_LAME_COPYRIGHT_SUFFIX = (
    "/*\n"
    " * This file was not generated by the swinfo2header utility.\n"
    " */\n"
)


class SopcCreateHeaderFilesImitator(AbstractSopcGenerator):
    """
    Generates sopc-create-header-files compatible C headers.
    Port of sopc2dts.generators.SopcCreateHeaderFilesImitator.
    """

    def __init__(self, sys: "AvalonSystem") -> None:
        super().__init__(sys, is_text=True)
        self._handled: Set[int] = set()

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    def _dump_component(self, comp: "BasicComponent", pov: Optional[str]) -> str:
        prefix = ""
        if not pov or comp.instance_name.lower() != pov.lower():
            prefix = self.definenify(comp.instance_name) + "_"

        res = (
            f"/*\n"
            f" * Macros for module '{comp.instance_name}',"
            f" class '{comp.class_name}'.\n"
        )
        if prefix:
            res += (
                f" * The macros are prefixed with '{prefix}'.\n"
                f" * The prefix is the slave descriptor.\n"
            )
        else:
            res += " * The macros have no prefix.\n"
        res += " */\n"

        if not pov or comp.instance_name.lower() != pov.lower():
            res += (
                f"#define {prefix}COMPONENT_TYPE {comp.class_name}\n"
                f"#define {prefix}COMPONENT_NAME {comp.instance_name}\n"
            )

        for param in comp.params:
            if param.name.upper().startswith("EMBEDDEDSW.CMACRO."):
                macro = self.definenify(param.name[18:])
                val_str = f" {param.value}" if param.value is not None else ""
                res += f"#define {prefix}{macro}{val_str}\n"

        return res + "\n"

    def _dump_children(self, master: "BasicComponent", pov: Optional[str]) -> str:
        res = ""
        for intf in master.interfaces:
            if not intf.is_memory_master():
                continue
            for conn in intf.connections:
                slave_intf = conn.slave_interface
                if slave_intf is None or id(slave_intf) in self._handled:
                    continue
                self._handled.add(id(slave_intf))
                slave = conn.slave_module
                if slave is None:
                    continue
                if slave.scd.group.lower() != "bridge":
                    res += self._dump_component(slave, pov)
                else:
                    res += self._dump_children(slave, pov)
        return res

    # ------------------------------------------------------------------
    # AbstractSopcGenerator interface
    # ------------------------------------------------------------------

    def get_text_output(self, bi: "BoardInfo") -> Optional[str]:
        self._handled.clear()
        pov = bi.get_pov() or None

        lame_copyright = _LAME_COPYRIGHT_SUFFIX + self._copyright_notice

        if not pov:
            # No POV — dump every non-bridge component
            res: Optional[str] = None
            for comp in self.sys.components:
                if comp.scd.group.lower() == "bridge":
                    continue
                if res is None:
                    res = (
                        "#ifndef _ALTERA_CPU_H_\n"
                        "#define _ALTERA_CPU_H_\n\n"
                        + lame_copyright
                    )
                res += self._dump_component(comp, pov)
            if res is not None:
                res += "\n#endif //_ALTERA_CPU_H_\n"
            return res

        # POV specified — dump POV component + all slaves
        pov_comp = self.sys.get_component_by_name(pov)
        if pov_comp is None:
            return None

        guard = "_ALTERA_" + self.definenify(pov) + "_H_"
        master_list = "\n".join(
            f" *   {intf.name}"
            for intf in pov_comp.interfaces
            if intf.is_memory_master()
        )
        res = (
            f"#ifndef {guard}\n"
            f"#define {guard}\n\n"
            + lame_copyright
            + "\n/*\n"
            f" * This file contains macros for module '{pov}' and devices\n"
            " * connected to the following masters:\n"
            + master_list + "\n"
            " * \n"
            " * Do not include this header file and another header file created for a\n"
            " * different module or master group at the same time.\n"
            " * Doing so may result in duplicate macro names.\n"
            " * Instead, use the system header file which has macros with unique names.\n"
            " */\n\n"
            + self._dump_component(pov_comp, pov)
            + self._dump_children(pov_comp, pov)
            + f"\n#endif /* {guard} */\n"
        )
        return res
